name: simple_package
description: "Simple generation package"
version: 0.0.3
homepage: "https://github.com/jinhan38/simple_package"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

executables:
  simple_generate: simple_generate

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
